// Standard styrke-øvelsesbibliotek (Fase 80).
// Statisk i kode — IKKE i DB. Hele systemet nøkler øvelser på fritekst-navn
// (workout_activity_exercises.exercise_name), så et seedet bibliotek gir mest
// verdi som en rik søkekilde i autocomplete, ved siden av brukerens eget
// user_exercises-bibliotek. Egne øvelser auto-upsertes fortsatt ved lagring.
//
// Kategoriene her er etter muskelgruppe/bevegelsesmønster (for søk/bla), mens
// «type økt» (Sirkel/Maksstyrke) fortsatt ligger på selve aktiviteten
// (movement_subcategory). De utholdenhetsspesifikke (staking, imitasjon,
// hoftestabilitet) er et reelt differensieringspunkt mot rene styrkeapper.

export type StandardExerciseCategory =
  | 'bein'
  | 'hofte'
  | 'press'
  | 'trekk'
  | 'core'
  | 'olympisk'
  | 'baere'
  | 'plyo'
  | 'prehab'
  | 'spesifikk'

export const STANDARD_EXERCISE_CATEGORIES: { key: StandardExerciseCategory; label: string }[] = [
  { key: 'bein',      label: 'Bein / forside lår' },
  { key: 'hofte',     label: 'Hofte / bakside / glutes' },
  { key: 'press',     label: 'Overkropp – press' },
  { key: 'trekk',     label: 'Overkropp – trekk' },
  { key: 'core',      label: 'Kjerne / core' },
  { key: 'olympisk',  label: 'Helkropp / olympisk' },
  { key: 'baere',     label: 'Bæring / grep' },
  { key: 'plyo',      label: 'Plyometrisk / spenst' },
  { key: 'prehab',    label: 'Stabilitet / mobilitet' },
  { key: 'spesifikk', label: 'Utholdenhetsspesifikk' },
]

export interface StandardExercise {
  name: string
  category: StandardExerciseCategory
}

export const STANDARD_EXERCISES: StandardExercise[] = [
  // ── Bein / forside lår ──────────────────────────────────
  { name: 'Knebøy', category: 'bein' },
  { name: 'Frontbøy', category: 'bein' },
  { name: 'Goblet squat', category: 'bein' },
  { name: 'Splitt-knebøy', category: 'bein' },
  { name: 'Bulgarsk utfall', category: 'bein' },
  { name: 'Gående utfall', category: 'bein' },
  { name: 'Utfall', category: 'bein' },
  { name: 'Beinpress', category: 'bein' },
  { name: 'Step-up', category: 'bein' },
  { name: 'Pistol squat', category: 'bein' },
  { name: 'Box squat', category: 'bein' },
  { name: 'Overhead squat', category: 'bein' },
  { name: 'Sissy squat', category: 'bein' },
  { name: 'Hack squat', category: 'bein' },
  { name: 'Zercher squat', category: 'bein' },
  { name: 'Beinekstensjon (maskin)', category: 'bein' },
  { name: 'Trap bar markløft', category: 'bein' },
  { name: 'Smith-maskin knebøy', category: 'bein' },
  { name: 'Belt squat', category: 'bein' },
  { name: 'Spanish squat (strikk bak kne)', category: 'bein' },
  { name: 'Cyclist squat (hæler hevet)', category: 'bein' },
  { name: 'Cossack squat', category: 'bein' },
  { name: 'Skater squat', category: 'bein' },
  { name: 'Step-down (eksentrisk fra kasse)', category: 'bein' },
  { name: 'Reverse nordic', category: 'bein' },
  { name: 'Sled push (prowler)', category: 'bein' },
  { name: 'Sled drag (baklengs)', category: 'bein' },
  { name: 'Adduktormaskin', category: 'bein' },
  { name: 'Ettbens beinpress', category: 'bein' },
  { name: 'Dobbel-kettlebell frontbøy', category: 'bein' },
  { name: 'Sandbag gående utfall (Hyrox)', category: 'bein' },
  { name: 'Overhead gående utfall (stang/plate)', category: 'bein' },

  // ── Hofte / bakside / glutes ────────────────────────────
  { name: 'Markløft', category: 'hofte' },
  { name: 'Rumensk markløft', category: 'hofte' },
  { name: 'Sumo markløft', category: 'hofte' },
  { name: 'Strak-bein markløft', category: 'hofte' },
  { name: 'Hip thrust', category: 'hofte' },
  { name: 'Glute bridge', category: 'hofte' },
  { name: 'Good morning', category: 'hofte' },
  { name: 'Kettlebell swing', category: 'hofte' },
  { name: 'Nordic hamstring curl', category: 'hofte' },
  { name: 'Single-leg romersk markløft', category: 'hofte' },
  { name: 'Rygghev / hyperekstensjon', category: 'hofte' },
  { name: 'Baklår-curl (maskin)', category: 'hofte' },
  { name: 'Ettbens markløft', category: 'hofte' },
  { name: 'Rack pull', category: 'hofte' },
  { name: 'Deficit markløft', category: 'hofte' },
  { name: 'Cable pull-through', category: 'hofte' },
  { name: 'Ettbens hip thrust', category: 'hofte' },
  { name: 'Frog pumps', category: 'hofte' },
  { name: 'Glute kickback (kabel)', category: 'hofte' },
  { name: 'Reverse hyperextension', category: 'hofte' },
  { name: 'B-stance markløft', category: 'hofte' },
  { name: '45° rygghev (ettbens)', category: 'hofte' },
  { name: 'Glute-ham raise (GHD)', category: 'hofte' },
  { name: 'Sumo deadlift high pull', category: 'hofte' },

  // ── Overkropp – press ───────────────────────────────────
  { name: 'Benkpress', category: 'press' },
  { name: 'Skråbenk benkpress', category: 'press' },
  { name: 'Manualpress', category: 'press' },
  { name: 'Stående skulderpress', category: 'press' },
  { name: 'Push press', category: 'press' },
  { name: 'Militærpress', category: 'press' },
  { name: 'Push-ups', category: 'press' },
  { name: 'Dips', category: 'press' },
  { name: 'Smale push-ups', category: 'press' },
  { name: 'Pike push-up', category: 'press' },
  { name: 'Håndstående push-up', category: 'press' },
  { name: 'Triceps pushdown', category: 'press' },
  { name: 'Triceps extension', category: 'press' },
  { name: 'Sidehev (lateral raise)', category: 'press' },
  { name: 'Arnold press', category: 'press' },
  { name: 'Landmine press', category: 'press' },
  { name: 'Ettarms landmine press', category: 'press' },
  { name: 'Floor press', category: 'press' },
  { name: 'Flies (manualer)', category: 'press' },
  { name: 'Kabel flies', category: 'press' },
  { name: 'Maskinflies (pec deck)', category: 'press' },
  { name: 'Frontheving', category: 'press' },
  { name: 'Overhead triceps extension (kabel)', category: 'press' },
  { name: 'Ring dips', category: 'press' },
  { name: 'Z-press (sittende gulvpress)', category: 'press' },
  { name: 'Skråbenk manualpress', category: 'press' },
  { name: 'Sittende skulderpress (manualer)', category: 'press' },
  { name: 'Chest press (maskin)', category: 'press' },
  { name: 'Skulderpress (maskin)', category: 'press' },
  { name: 'Benk-dips (bench dips)', category: 'press' },
  { name: 'Deficit push-ups', category: 'press' },
  { name: 'Kettlebell push press', category: 'press' },

  // ── Overkropp – trekk ───────────────────────────────────
  { name: 'Pull-ups', category: 'trekk' },
  { name: 'Chin-ups', category: 'trekk' },
  { name: 'Nedtrekk (lat pulldown)', category: 'trekk' },
  { name: 'Stående roing (barbell row)', category: 'trekk' },
  { name: '1-arm manualroing', category: 'trekk' },
  { name: 'Sittende kabelroing', category: 'trekk' },
  { name: 'T-bar row', category: 'trekk' },
  { name: 'Pendlay row', category: 'trekk' },
  { name: 'Inverted row', category: 'trekk' },
  { name: 'Face pull', category: 'trekk' },
  { name: 'Band pull-apart', category: 'trekk' },
  { name: 'Biceps curl', category: 'trekk' },
  { name: 'Hammer curl', category: 'trekk' },
  { name: 'Renegade row', category: 'trekk' },
  { name: 'Straight-arm pulldown (rett arm — stakespesifikk)', category: 'trekk' },
  { name: 'Chest-supported row (brystliggende roing)', category: 'trekk' },
  { name: 'Seal row', category: 'trekk' },
  { name: 'Meadows row', category: 'trekk' },
  { name: 'Shrugs', category: 'trekk' },
  { name: 'Omvendt flyes (bakre skulder)', category: 'trekk' },
  { name: 'Kabel omvendt flyes', category: 'trekk' },
  { name: 'Upright row', category: 'trekk' },
  { name: 'Pullover (manual)', category: 'trekk' },
  { name: 'Scapula pull-ups', category: 'trekk' },
  { name: 'Dead hang (henge i stang)', category: 'trekk' },
  { name: 'Preacher curl', category: 'trekk' },
  { name: 'Konsentrasjonscurl', category: 'trekk' },
  { name: 'Zottman curl', category: 'trekk' },
  { name: 'Maskinroing (chest-supported)', category: 'trekk' },
  { name: 'Assistert pull-up (maskin/strikk)', category: 'trekk' },
  { name: 'Chest-to-bar pull-ups', category: 'trekk' },
  { name: 'EZ-bar curl', category: 'trekk' },
  { name: 'Kabelcurl', category: 'trekk' },

  // ── Kjerne / core ───────────────────────────────────────
  { name: 'Planke', category: 'core' },
  { name: 'Sideplanke', category: 'core' },
  { name: 'Hollow hold', category: 'core' },
  { name: 'Dead bug', category: 'core' },
  { name: 'Bird dog', category: 'core' },
  { name: 'Pallof press', category: 'core' },
  { name: 'Ab wheel rollout', category: 'core' },
  { name: 'Hanging leg raise', category: 'core' },
  { name: 'Toes-to-bar', category: 'core' },
  { name: 'V-ups', category: 'core' },
  { name: 'Russian twist', category: 'core' },
  { name: 'Cable woodchop', category: 'core' },
  { name: 'Sit-ups', category: 'core' },
  { name: 'Crunch', category: 'core' },
  { name: 'Mountain climbers', category: 'core' },
  { name: 'L-sit', category: 'core' },
  { name: 'Skuldertapp-planke', category: 'core' },
  { name: 'GHD sit-up', category: 'core' },
  { name: 'Cable crunch', category: 'core' },
  { name: 'Weighted planke', category: 'core' },
  { name: 'Body saw', category: 'core' },
  { name: 'Stir the pot (planke på ball)', category: 'core' },
  { name: 'Planke m/ drag (plate pull-through)', category: 'core' },
  { name: 'Windshield wipers', category: 'core' },
  { name: 'Flutter kicks', category: 'core' },
  { name: 'Bicycle crunch', category: 'core' },
  { name: 'Superman-hold', category: 'core' },
  { name: 'Side bend (manual)', category: 'core' },
  { name: 'Dragon flag', category: 'core' },
  { name: 'Landmine rotasjon', category: 'core' },
  { name: 'Suitcase hold (statisk sidebæring)', category: 'core' },
  { name: 'Kettlebell windmill', category: 'core' },
  { name: 'Kettlebell halo', category: 'core' },
  { name: 'Hollow rocks', category: 'core' },
  { name: 'Ring support hold', category: 'core' },

  // ── Helkropp / olympisk ─────────────────────────────────
  { name: 'Frivending (clean)', category: 'olympisk' },
  { name: 'Power clean', category: 'olympisk' },
  { name: 'Hang clean', category: 'olympisk' },
  { name: 'Clean & jerk', category: 'olympisk' },
  { name: 'Rykk (snatch)', category: 'olympisk' },
  { name: 'Power snatch', category: 'olympisk' },
  { name: 'Thruster', category: 'olympisk' },
  { name: 'Wall ball', category: 'olympisk' },
  { name: 'Burpee', category: 'olympisk' },
  { name: 'Kettlebell clean', category: 'olympisk' },
  { name: 'Devil press', category: 'olympisk' },
  { name: 'Man maker', category: 'olympisk' },
  { name: 'Turkish get-up', category: 'olympisk' },
  { name: 'Snatch-grep markløft', category: 'olympisk' },
  { name: 'Hang snatch', category: 'olympisk' },
  { name: 'Clean pull', category: 'olympisk' },
  { name: 'Snatch pull', category: 'olympisk' },
  { name: 'Push jerk', category: 'olympisk' },
  { name: 'Split jerk', category: 'olympisk' },
  { name: 'Sandbag til skulder', category: 'olympisk' },
  { name: 'Sandbag bear hug squat', category: 'olympisk' },
  { name: 'Sandbag squat-to-press', category: 'olympisk' },
  { name: 'Wall walk', category: 'olympisk' },
  { name: 'Battle ropes', category: 'olympisk' },
  { name: 'Medisinball clean', category: 'olympisk' },
  { name: 'Muscle-up (ringer/stang)', category: 'olympisk' },
  { name: 'Rope climb (tauklatring)', category: 'olympisk' },
  { name: 'Handstand hold (mot vegg)', category: 'olympisk' },
  { name: 'Handstand walk', category: 'olympisk' },
  { name: 'Box step-over m/ vekt', category: 'olympisk' },
  { name: 'Burpee broad jump (Hyrox)', category: 'olympisk' },
  { name: 'Burpee box jump-over', category: 'olympisk' },
  { name: 'Burpee pull-up', category: 'olympisk' },
  { name: 'Kettlebell snatch', category: 'olympisk' },

  // ── Bæring / grep ───────────────────────────────────────
  { name: 'Farmer\'s walk', category: 'baere' },
  { name: 'Suitcase carry (énarms)', category: 'baere' },
  { name: 'Overhead carry', category: 'baere' },
  { name: 'Front rack carry', category: 'baere' },
  { name: 'Zercher carry', category: 'baere' },
  { name: 'Sled pull m/ tau (hand-over-hand)', category: 'baere' },
  { name: 'Plate pinch (grep)', category: 'baere' },
  { name: 'Towel pull-ups (håndkle-grep)', category: 'baere' },
  { name: 'Håndleddscurl', category: 'baere' },
  { name: 'Omvendt håndleddscurl', category: 'baere' },
  { name: 'D-ball/stein til fang (heavy pick-up)', category: 'baere' },

  // ── Plyometrisk / spenst ────────────────────────────────
  { name: 'Box jump', category: 'plyo' },
  { name: 'Knebøyhopp', category: 'plyo' },
  { name: 'Utfallshopp', category: 'plyo' },
  { name: 'Bredhopp (broad jump)', category: 'plyo' },
  { name: 'Skøytehopp (lateral bounds)', category: 'plyo' },
  { name: 'Tuck jump', category: 'plyo' },
  { name: 'Depth jump', category: 'plyo' },
  { name: 'Pogo hops', category: 'plyo' },
  { name: 'Ettbens hopp', category: 'plyo' },
  { name: 'Hekkhopp', category: 'plyo' },
  { name: 'Klapp-push-ups', category: 'plyo' },
  { name: 'Medisinball slam', category: 'plyo' },
  { name: 'Medisinball rotasjonskast', category: 'plyo' },
  { name: 'Sprint-akselerasjon', category: 'plyo' },
  { name: 'Steghopp (bounding)', category: 'plyo' },
  { name: 'Steghopp i motbakke', category: 'plyo' },
  { name: 'Lateral hekkhopp', category: 'plyo' },
  { name: 'Ettbens lateral hopp', category: 'plyo' },
  { name: 'Drop til stopp (landingskontroll)', category: 'plyo' },
  { name: 'Medisinball brystpasning (eksplosiv)', category: 'plyo' },
  { name: 'Medisinball kast over hodet bakover', category: 'plyo' },
  { name: 'Approach jump (tilløpshopp)', category: 'plyo' },
  { name: 'Split jump m/ manualer', category: 'plyo' },
  { name: 'Double-unders (hopptau)', category: 'plyo' },
  { name: 'Hopptau (single-unders)', category: 'plyo' },

  // ── Stabilitet / mobilitet / prehab ─────────────────────
  { name: 'Sidehev hofte (abduksjon)', category: 'prehab' },
  { name: 'Monster walk (strikk)', category: 'prehab' },
  { name: 'Clamshell', category: 'prehab' },
  { name: 'Copenhagen plank (adduktor)', category: 'prehab' },
  { name: 'Ettbens balanse', category: 'prehab' },
  { name: 'Tåhev / leggheving (calf raise)', category: 'prehab' },
  { name: 'Single-leg calf raise', category: 'prehab' },
  { name: 'Wall sit', category: 'prehab' },
  { name: 'Bjørnegange (bear crawl)', category: 'prehab' },
  { name: 'Skulder Y-T-W', category: 'prehab' },
  { name: 'Tå- og hælgange', category: 'prehab' },
  { name: 'Tibialis-løft (skinnben)', category: 'prehab' },
  { name: 'Hoftebøyer-mobilitet', category: 'prehab' },
  { name: 'Sittende tåhev (soleus)', category: 'prehab' },
  { name: 'Eksentrisk tåhev (langsomt ned)', category: 'prehab' },
  { name: 'Tåhev i trapp (full ROM)', category: 'prehab' },
  { name: 'Knee-to-wall ankelmobilitet', category: 'prehab' },
  { name: 'Ankel-dorsalfleksjon m/ strikk', category: 'prehab' },
  { name: 'Hip airplane', category: 'prehab' },
  { name: '90/90 hofterotasjon', category: 'prehab' },
  { name: 'Utadrotasjon skulder (strikk)', category: 'prehab' },
  { name: 'Innadrotasjon skulder (strikk)', category: 'prehab' },
  { name: 'Scapula push-up', category: 'prehab' },
  { name: 'Wall slides', category: 'prehab' },
  { name: 'Thorakal rotasjon (åpne boka)', category: 'prehab' },
  { name: 'Ettbens knebøy på balansepute', category: 'prehab' },
  { name: 'Nordic curl eksentrisk (assistert)', category: 'prehab' },

  // ── Utholdenhetsspesifikk (langrenn / ski / løp / skiskyting) ──
  { name: 'Staking med strikk', category: 'spesifikk' },
  { name: 'Staking med kabel', category: 'spesifikk' },
  { name: 'Stakemaskin (SkiErg)', category: 'spesifikk' },
  { name: 'Sittende stake-pulls', category: 'spesifikk' },
  { name: 'Dobbeldans-imitasjon', category: 'spesifikk' },
  { name: 'Diagonal-imitasjon med staver', category: 'spesifikk' },
  { name: 'Hoftebøyer-løft (løpsspesifikk)', category: 'spesifikk' },
  { name: 'A-skip', category: 'spesifikk' },
  { name: 'B-skip', category: 'spesifikk' },
  { name: 'Ankel/legg-hopp (stivhet)', category: 'spesifikk' },
  { name: 'Statisk holdning/balanse for skyting', category: 'spesifikk' },
  { name: 'Pust- og holdningsstabilitet', category: 'spesifikk' },
  { name: 'Ettarms staking i kabel', category: 'spesifikk' },
  { name: 'Stakedrag m/ strikk – høy frekvens', category: 'spesifikk' },
  { name: 'Stakedrag liggende på ball (core + stake)', category: 'spesifikk' },
  { name: 'Skøyte-imitasjon m/ strikk (sideveis fraspark)', category: 'spesifikk' },
  { name: 'Stegimitasjon m/ staver (sprunglauf)', category: 'spesifikk' },
  { name: 'Høye kneløft m/ strikk (løpsdriv)', category: 'spesifikk' },
  { name: 'Geværløft (reps, tomt gevær/stang)', category: 'spesifikk' },
  { name: 'Skytestilling stående på balansepute', category: 'spesifikk' },
  { name: 'Skytestilling-hold etter pulsdrag (kombinasjon)', category: 'spesifikk' },
  { name: 'Tørravtrekk m/ høy puls', category: 'spesifikk' },
  { name: 'Liggende skytestilling-hold (albuestabilitet)', category: 'spesifikk' },
  { name: 'Ettbens balanse m/ geværhold', category: 'spesifikk' },
  { name: 'Svømmedrag m/ strikk (dryland)', category: 'spesifikk' },
  { name: 'Ettarms svømmedrag i kabel', category: 'spesifikk' },
  { name: 'Svømmedrag på ball (prone Y-drag)', category: 'spesifikk' },
  { name: 'Streamline-hold m/ strikk (overhead-stabilitet)', category: 'spesifikk' },
  { name: 'Vasa/svømmebenk-drag', category: 'spesifikk' },
  { name: 'Step-up m/ pedaltråkk-driv (høy kasse, ettbens)', category: 'spesifikk' },
  { name: 'Isometrisk ettbens wall sit (sykkelposisjon)', category: 'spesifikk' },
  { name: 'Hip flexor march m/ strikk (tråkkløft)', category: 'spesifikk' },
  { name: 'Romaskin (stasjon)', category: 'spesifikk' },
  { name: 'Assault bike (stasjon)', category: 'spesifikk' },
]

const NORMALIZE = (s: string) => s.trim().toLowerCase()

// Søk i standardbiblioteket på navn-substring. excludeNames (normalisert) lar
// kalleren droppe øvelser som allerede finnes i brukerens eget bibliotek/forslag.
export function searchStandardExercises(
  query: string,
  excludeNames: Set<string> = new Set(),
  limit = 8,
): StandardExercise[] {
  const q = NORMALIZE(query)
  if (!q) return []
  const out: StandardExercise[] = []
  for (const ex of STANDARD_EXERCISES) {
    if (excludeNames.has(NORMALIZE(ex.name))) continue
    if (NORMALIZE(ex.name).includes(q)) out.push(ex)
    if (out.length >= limit) break
  }
  return out
}
